--
-- PostgreSQL database dump
--

\restrict iWNM8y5RcX4Sp22JUIbNuESJT1TPQp8B0K8GvLhke7vacKgopQ57HgaCSHN7gY2

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    id_users bigint NOT NULL,
    money numeric(38,2)
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- Name: accounts_id_users_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts ALTER COLUMN id_users ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_users_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts (id_users, money) FROM stdin;
1	0.00
2	1000.00
3	1000.00
4	1000.00
\.


--
-- Name: accounts_id_users_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_id_users_seq', 1, false);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id_users);


--
-- PostgreSQL database dump complete
--

\unrestrict iWNM8y5RcX4Sp22JUIbNuESJT1TPQp8B0K8GvLhke7vacKgopQ57HgaCSHN7gY2

