--
-- PostgreSQL database dump
--

\restrict Y70neddVDVXH5Ej00kqyhqw0yw3JmGKGYM4zDD2Hk6zH9mYKjfxUhHzbFnWWMBq

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    id_users bigint NOT NULL,
    money numeric(38,2)
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- Name: accounts_id_users_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts ALTER COLUMN id_users ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_users_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: operations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.operations (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    type integer NOT NULL,
    amount numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone,
    CONSTRAINT operations_amount_check CHECK ((amount > (0)::numeric)),
    CONSTRAINT operations_type_check CHECK ((type = ANY (ARRAY[1, 2, 3, 4])))
);


ALTER TABLE public.operations OWNER TO postgres;

--
-- Name: operations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.operations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.operations_id_seq OWNER TO postgres;

--
-- Name: operations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.operations_id_seq OWNED BY public.operations.id;


--
-- Name: operations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operations ALTER COLUMN id SET DEFAULT nextval('public.operations_id_seq'::regclass);


--
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts (id_users, money) FROM stdin;
4	1000.00
3	5000.00
1	0.00
2	8000.00
\.


--
-- Data for Name: operations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.operations (id, user_id, type, amount, created_at) FROM stdin;
1	1	1	1000.00	\N
2	1	1	1000.00	\N
3	1	1	1000.00	\N
4	1	1	1000.00	\N
5	2	1	1000.00	2025-12-14 10:15:53.413869
6	2	1	1000.00	2025-12-14 10:15:54.236849
7	2	1	1000.00	2025-12-14 10:15:54.824706
8	2	1	1000.00	2025-12-14 10:15:55.261625
9	2	1	1000.00	2025-12-14 10:15:56.742456
10	3	1	1000.00	2025-12-14 20:57:55.624556
11	3	1	1000.00	2025-12-14 20:57:56.640676
12	3	1	1000.00	2025-12-14 20:57:57.648543
13	3	1	1000.00	2025-12-14 20:57:59.526878
16	1	2	1000.00	2025-12-15 00:24:23.478459
17	1	2	1000.00	2025-12-15 00:24:25.31363
18	1	3	1000.00	2025-12-15 00:26:47.607036
19	1	4	1000.00	2025-12-15 00:26:47.608036
20	1	3	1000.00	2025-12-15 00:27:02.733203
21	1	4	1000.00	2025-12-15 00:27:02.734204
22	1	3	1000.00	2025-12-15 00:27:03.353997
23	1	4	1000.00	2025-12-15 00:27:03.354998
24	1	3	1000.00	2025-12-15 00:27:03.957192
25	1	4	1000.00	2025-12-15 00:27:03.957192
26	1	3	1000.00	2025-12-15 00:27:04.55068
27	1	4	1000.00	2025-12-15 00:27:04.551683
28	1	3	1000.00	2025-12-15 00:27:05.151325
29	1	4	1000.00	2025-12-15 00:27:05.151325
30	1	3	1000.00	2025-12-15 00:27:05.76867
31	1	4	1000.00	2025-12-15 00:27:05.769671
32	1	3	1000.00	2025-12-15 00:27:06.317564
33	1	4	1000.00	2025-12-15 00:27:06.318561
34	1	3	1000.00	2025-12-15 00:27:06.860192
35	1	4	1000.00	2025-12-15 00:27:06.861195
36	1	3	1000.00	2025-12-15 00:27:07.404642
37	1	4	1000.00	2025-12-15 00:27:07.404642
38	1	3	1000.00	2025-12-15 00:27:07.900391
39	1	4	1000.00	2025-12-15 00:27:07.901393
40	1	3	1000.00	2025-12-15 00:27:08.39297
41	1	4	1000.00	2025-12-15 00:27:08.39297
42	1	3	1000.00	2025-12-15 00:27:08.919345
43	1	4	1000.00	2025-12-15 00:27:08.919345
44	1	3	1000.00	2025-12-15 00:27:09.339009
45	1	4	1000.00	2025-12-15 00:27:09.340007
46	1	3	1000.00	2025-12-15 00:27:09.866051
47	1	4	1000.00	2025-12-15 00:27:09.867051
48	1	3	1000.00	2025-12-15 00:27:10.332763
49	1	4	1000.00	2025-12-15 00:27:10.333763
50	1	3	1000.00	2025-12-15 00:27:10.737742
51	1	4	1000.00	2025-12-15 00:27:10.738741
52	1	3	1000.00	2025-12-15 00:27:11.340982
53	1	4	1000.00	2025-12-15 00:27:11.341982
54	1	3	1000.00	2025-12-15 00:27:39.790082
55	1	4	1000.00	2025-12-15 00:27:39.791084
56	1	3	1000.00	2025-12-15 00:27:40.440315
57	1	4	1000.00	2025-12-15 00:27:40.441316
58	1	3	1000.00	2025-12-15 00:27:41.002008
59	1	4	1000.00	2025-12-15 00:27:41.00301
60	1	3	1000.00	2025-12-15 00:27:48.827292
61	1	4	1000.00	2025-12-15 00:27:48.828293
62	1	3	1000.00	2025-12-15 01:36:00.27095
63	1	4	1000.00	2025-12-15 01:36:00.289946
64	1	3	1000.00	2025-12-15 01:36:01.468183
65	1	4	1000.00	2025-12-15 01:36:01.469183
66	1	3	1000.00	2025-12-15 01:36:02.210644
67	1	4	1000.00	2025-12-15 01:36:02.211646
68	1	3	1000.00	2025-12-15 01:36:02.969699
69	1	4	1000.00	2025-12-15 01:36:02.970699
70	1	3	1000.00	2025-12-15 01:36:03.544323
71	1	4	1000.00	2025-12-15 01:36:03.545322
72	1	3	1000.00	2025-12-15 01:36:04.197402
73	1	4	1000.00	2025-12-15 01:36:04.198402
74	1	3	1000.00	2025-12-15 01:36:04.820556
75	1	4	1000.00	2025-12-15 01:36:04.821556
76	1	3	1000.00	2025-12-15 01:36:05.424337
77	1	4	1000.00	2025-12-15 01:36:05.425337
78	1	3	1000.00	2025-12-15 01:36:06.042688
79	1	4	1000.00	2025-12-15 01:36:06.043689
80	1	3	1000.00	2025-12-15 01:36:06.630887
81	1	4	1000.00	2025-12-15 01:36:06.631885
82	1	3	1000.00	2025-12-15 01:36:44.889128
83	1	4	1000.00	2025-12-15 01:36:44.889128
84	1	3	1000.00	2025-12-15 01:36:52.569866
85	1	4	1000.00	2025-12-15 01:36:52.570867
86	1	3	1000.00	2025-12-15 01:40:52.472261
87	2	4	1000.00	2025-12-15 01:40:52.48726
88	1	3	1000.00	2025-12-15 01:41:07.259283
89	2	4	1000.00	2025-12-15 01:41:07.259283
\.


--
-- Name: accounts_id_users_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_id_users_seq', 1, false);


--
-- Name: operations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.operations_id_seq', 89, true);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id_users);


--
-- Name: operations operations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT operations_pkey PRIMARY KEY (id);


--
-- Name: operations operations_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT operations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.accounts(id_users);


--
-- PostgreSQL database dump complete
--

\unrestrict Y70neddVDVXH5Ej00kqyhqw0yw3JmGKGYM4zDD2Hk6zH9mYKjfxUhHzbFnWWMBq

